# Generated by Django 5.0 on 2024-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
