# Generated by Django 5.0.1 on 2024-05-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=123)),
                ('is_completes', models.BooleanField(default=False)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updates_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
