# Generated by Django 5.0 on 2024-06-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_demo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
